### PR TITLE
Added support for unique env vars per peer and orderer + Typo fix

### PR DESCRIPTION
**Pull request by runitmisra**
Implements #12

### CODE REVIEW

**Comment by runitmisra** [comment]
@tittuvarghese @jithindevasia @siddharthmakwana Please help review and merge

**Comment by runitmisra** [comment]
Not sure if we should consider this "not backwards compatible" as I have fixed a typo in the values and templates for the word `additional`. People using the old values files will have to change this.

**Comment by tittuvarghese** [comment]
@runitmisra , There is one release pending from @jithindevasia  it has some breaking changes. We can club together during that release.

**Comment by jithindevasia** [comment]
Merging to release branch for further testing. If the functionalities are working as expected, we will include this feature in the next release v1.1.0.

**Pull request merged**
